version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typedoc
    versions:
    - 0.20.16
    - 0.20.23
    - 0.20.25
    - 0.20.28
    - 0.20.32
    - 0.20.33
    - 0.20.34
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.22
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.31
    - 14.14.33
    - 14.14.36
    - 14.14.37
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.0.8
    - 31.6.1
    - 32.2.0
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: typeson-registry
    versions:
    - 1.0.0-alpha.38
- package-ecosystem: npm
  directory: "/examples/next-kittens"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/plugin-transform-react-jsx"
    versions:
    - 7.12.1
