version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    allowed_updates:
      - match:
          dependency_type: all
          update_type: all
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:minor
    version_requirement_updates: increase_versions

  - package_manager: javascript
    directory: /examples/next-kittens/
    update_schedule: weekly
    allowed_updates:
      - match:
          dependency_type: all
          update_type: all
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:minor
    version_requirement_updates: increase_versions
