export type StringProperties =
  | number
  | "toString"
  | "valueOf"
  | "charAt"
  | "charCodeAt"
  | "concat"
  | "indexOf"
  | "lastIndexOf"
  | "localeCompare"
  | "match"
  | "replace"
  | "search"
  | "slice"
  | "split"
  | "substring"
  | "toLowerCase"
  | "toLocaleLowerCase"
  | "toUpperCase"
  | "toLocaleUpperCase"
  | "trim"
  | "length"
  | "substr"
  | "codePointAt"
  | "includes"
  | "endsWith"
  | "normalize"
  | "repeat"
  | "startsWith"
  | "anchor"
  | "big"
  | "blink"
  | "bold"
  | "fixed"
  | "fontcolor"
  | "fontsize"
  | "italics"
  | "link"
  | "small"
  | "strike"
  | "sub"
  | "sup"
  | "padStart"
  | "padEnd"
  | "trimLeft"
  | "trimRight";

export type NumberProperties =
  | "toString"
  | "toFixed"
  | "toExponential"
  | "toPrecision"
  | "valueOf"
  | "toLocaleString";

export type BooleanProperties = "valueOf";
